<?php get_header(); ?>
<div id="content">
    <div id="contentleft">
        <div class="postarea">
            <div class="breadcrumb">
                Browse &gt; 
                <!-- Breadcrumb, generated by 'Breadcrumb Nav XT' - http://mtekk.weblogs.us/code -->
                <?php if (function_exists('bcn_display')) { bcn_display(); } ?>
            </div>
            
            <?php while(have_posts()) : the_post(); ?>
            <h3 class="title"><a rel="bookmark" href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h3>
            <div class="date">
                <div class="dateleft">
                    <p><span class="time"><?php the_date(get_option( 'date_format' )); ?></span> by <?php the_author_posts_link(); ?></p>
                </div>
                <div class="dateright">
                    <p><span class="comment"><a title="Comment on <?php the_title(); ?>" href="<?php comments_link(); ?>"><?php comments_number( 'No Comments', 'One Comments', '% Comments' ); ?></a></span></p>
                </div>
            </div>
            <div><?php the_excerpt(); ?></div>
            <div style="clear:both;"></div>
            <?php endwhile; ?>
            
            <?php if(function_exists('getpagenavi')){ getpagenavi(); } ?>
        </div>

    </div>

    ﻿<!-- begin sidebar -->

    <?php get_sidebar(); ?>

    <!-- end sidebar -->		
</div>
<?php get_footer(); ?>