<?php get_header(); ?>
<div id="content">
    <div id="contentleft">
        <div class="postarea">
            <div class="breadcrumb">
                Browse &gt; 
                <!-- Breadcrumb, generated by 'Breadcrumb Nav XT' - http://mtekk.weblogs.us/code -->
                <?php if (function_exists('bcn_display')) { bcn_display(); } ?>
            </div>			

            <?php 
            $excludeID = array();
            while(have_posts()) : the_post(); 
                $excludeID = array(get_the_ID());
            ?>
            <h1><?php the_title(); ?></h1>
            <div class="post-content"><?php the_content(); ?></div>
            <div style="clear:both;"></div>

            <div class="postmeta">
                <p><span class="tags">Từ khóa: <?php the_tags(''); ?></span></p> 
                <p><span class="tags"> Chuyên mục: <?php the_category(', ') ?></span></p>
            </div>
            <?php endwhile; ?>
        </div>

        <div class="adsense-post">
            <!--To activate your Google AdSense ad, go to your WP dashboard and go to Presentation -> Revolution Music Options and enter your Google Adsense Code.-->
            <object width="480" height="60" id="86d0fcc781574993b6cebea3c64d251a" codebase="https://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000">
                <param value="http://imstore.bet365affiliates.com/365_003619-508-155-2-149-1-4576.aspx" name="movie">
                <param value="high" name="quality">
                <param value="transparent" name="wmode">
                <param value="always" name="allowScriptAccess">
                <param value="external" name="allowNetworking">
                <embed width="480" height="60" wmode="transparent" pluginspage="https://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" name="86d0fcc781574993b6cebea3c64d251a" swliveconnect="false" allownetworking="external" allowscriptaccess="always" quality="high" src="http://imstore.bet365affiliates.com/365_003619-508-155-2-149-1-4576.aspx">
            </object>					
        </div>
        <div class="related-post">
            <h2 class="related_post_title">Các bài viết cùng chủ đề</h2>
            <ul class="related_post">
                <?php
                $loop = new WP_Query(array(
                            'post_type' => 'post',
                            'posts_per_page' => 5,
                            'orderby' => 'rand',
                            'post__not_in' => $excludeID,
                        ));
                while ($loop->have_posts()) : $loop->the_post();
                ?>
                <li><a href="<?php the_permalink(); ?>" title="<?php the_title(); ?>"><?php the_title(); ?></a></li>
                <?php 
                endwhile;
                wp_reset_query(); 
                ?>
            </ul>
        </div>

        <?php comments_template(); ?>

    </div>

    ﻿<!-- begin sidebar -->

    <?php get_sidebar(); ?>

    <!-- end sidebar -->		
</div>
<?php get_footer(); ?>